name: deployment

on:
  push:
    branches:
    - '*'
    workflow_dispatch:

env:
  DB_NAME: smartchi-test
  DB_USERNAME: postgres
  DB_PASSWORD: postgres

jobs:
  testing:
    runs-on: ubuntu-latest
    container: node:latest
    env:
      DB_HOST: postgres
    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_DB: ${{env.DB_NAME}}
          POSTGRES_USERNAME: ${{env.DB_USERNAME}}
          POSTGRES_PASSWORD: ${{env.DB_PASSWORD}}
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     sudo: false
      - run: |
          yarn install
          yarn knex migrate:latest 
          yarn knex seed:run
          yarn jest --detectOpenHandles




##=================          yarn jest --detectOpenHandles===============##
## yarn knex migrate:latest##

  deploy:
    if: github.ref_name == 'production'
    runs-on: ubuntu-latest
    needs: testing
    steps:
    - uses: fifsky/ssh-action@master
      with:
        command: |
          cd BAD_Project
          git pull
          forever restart 0
        host: 18.142.208.18
        user: ubuntu
        key: ${{secrets.SSH_PRIVATE_KEY}}