name: deployment

on:
  push:
    branches:
    - '*'
    workflow_dispatch:

env:
  DB_NAME: smartchi-test
  DB_USERNAME: postgres
  DB_PASSWORD: postgres

jobs:
testing:
  runs-on: ubuntu-lastest
  container: mcr.microsoft.com/playwright:focal
  env:
    DB_HOST: postgres
  services:
    postgres:
      image: postgres
        env: 
          POSTGRES_DB: ${{env.DB_NAME}}
          POSTGRES_USERNAME: ${{env.DB_USERNAME}}
          POSTGRES_PASSWORD: ${{env.DB_PASSWORD}}
        ports:
          - 5432:5432
          steps:
          - uses: actions/checkout@v3
          # - name: Setup tmate session
          #   uses: mxschmitt/action-tmate@v3
          #   with:
          #     sudo: false
          - run: |
            yarn install
            yarn knex migrate:lastest
            yarn jest


##================================##



